version: "3.9"

services:
  pr-server:
    container_name: server
    image: vinipilan9999/proxy-reverse-server:2.0
    build: ./pr-server/
    read_only: true
    restart: always
    tmpfs:                 
      - /home  
      - /mnt   
      - /run   
      - /srv  
      - /tmp  
      - /boot  
      - /docker-entrypoint.d                    
      - /media  
      - /opt  
      - /root  
      - /sbin  
      - /sys  
      - /var/cache/nginx
    networks:
      - server
    ports:
      - 80:80
    depends_on:
      - mysql-adm
      - mongo-adm
    # volumes:
    #   - ./pr-server/conf.d/:/etc/nginx/conf.d/


  mongo-db:
    container_name: mongo-db
    image: mongo:6.0.1
    read_only: true
    restart: always
    tmpfs:
      - /tmp
      - /data
      - /home
      - /media  
      - /opt   
      - /root  
      - /sbin  
      - /sys  
      - /boot                            
      - /lib32  
      - /libx32  
      - /mnt    
      - /run   
      - /srv   
      - /var
      - /docker-entrypoint-initdb.d
    networks:
      - mongo
    volumes:
      - mongo-content:/data/db
      - mongo-config:/data/configdb
    environment:
      MONGO_INITDB_ROOT_USERNAME: vinicius
      MONGO_INITDB_ROOT_PASSWORD: 1234
  

  mongo-adm:
    container_name: mongo-adm
    image: mongo-express:1.0.0-alpha
    read_only: true
    restart: always
    tmpfs:
      - /etc
      - /tmp
      - /data
      - /home
      - /media  
      - /opt   
      - /root   
      - /sys              
      - /mnt    
      - /run   
      - /srv   
      - /var
    networks:
      - mongo
      - server
    depends_on:
      - mongo-db
    environment:
      ME_CONFIG_MONGODB_URL: mongodb://vinicius:1234@mongo-db:27017/
      ME_CONFIG_SITE_BASEURL: /nosql/
  

  mysql-db:
    container_name: mysql-db
    image: mysql:8.0.30
    read_only: true
    restart: always
    tmpfs:
      - /boot
      - /docker-entrypoint-initdb.d
      - /home
      - /lib
      - /media
      - /mnt
      - /opt
      - /root
      - /run
      - /srv
      - /sys
      - /tmp
      - /var
    networks:
      - mysql
    volumes:
      - mysql-content:/var/lib/mysql
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: 1 
      MYSQL_DATABASE: db
      MYSQL_USER: vinicius
      MYSQL_PASSWORD: 1234


  mysql-adm:
    container_name: mysql-adm
    image: adminer:4.8.1
    read_only: true
    restart: always
    tmpfs:
      - /etc    
      - /home    
      - /media  
      - /mnt    
      - /opt     
      - /root     
      - /sbin   
      - /srv   
      - /sys    
      - /tmp    
    networks:
      - mysql
      - server
    depends_on:
      - mysql-db
    environment:
      ADMINER_DEFAULT_SERVER: mysql-db



volumes:
  mongo-content:
  mongo-config:
  mysql-content:


networks:
  mongo:
  mysql:
  server: